services:
  skypulse:
    build:
      context: .
    ports:
      - '3000:${PORT:-3000}'
    env_file:
      - path: .env
        required: false
    environment:
      - NODE_ENV=production
      - SEED_DB=${SEED_DB:-false}
    restart: always
